name: Generate Ontology Docs with Ontospy

on:
  push:
    paths:
      - 'ontology/**'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Ontospy
      run: |
        pip install ontospy

    - name: Generate Ontospy HTML docs
      run: |
        mkdir -p docs
        ontospy gendocs ontology/graceful17.ttl -o docs --theme united --title "g17 Ontology" -f 2

    - name: Commit and push documentation
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs
        git commit -m "Update Ontospy documentation" || echo "No changes to commit"
        git push